// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoluntaMais.Api.Data;

#nullable disable

namespace VoluntaMais.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CategoriaVoluntario", b =>
                {
                    b.Property<long>("AreasAfinidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VoluntariosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AreasAfinidadeId", "VoluntariosId");

                    b.HasIndex("VoluntariosId");

                    b.ToTable("CategoriaVoluntario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Assistencia Social",
                            VersaoRegistro = new Guid("a0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Acolhimento Familiar",
                            VersaoRegistro = new Guid("a0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Inclusao",
                            VersaoRegistro = new Guid("a0000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Cuidado",
                            VersaoRegistro = new Guid("a0000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 5L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Formacao",
                            VersaoRegistro = new Guid("a0000001-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Autor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InscricaoId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Habilidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Acolhimento",
                            VersaoRegistro = new Guid("b0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Organizacao de eventos",
                            VersaoRegistro = new Guid("b0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Cuidado de criancas",
                            VersaoRegistro = new Guid("b0000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Atendimento a familias",
                            VersaoRegistro = new Guid("b0000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 5L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Apoio operacional",
                            VersaoRegistro = new Guid("b0000001-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Inscricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoReprovacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("OportunidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("VoluntarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoluntarioId");

                    b.HasIndex("OportunidadeId", "VoluntarioId")
                        .IsUnique();

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Instituicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Instituicoes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Acoes que promovem o protagonismo da pessoa com deficiencia e o cuidado a sua familia.",
                            Excluido = false,
                            Nome = "Instituto Vitor Gabriel",
                            Responsavel = "Instituto Vitor Gabriel",
                            Status = 1,
                            UsuarioId = 2L,
                            VersaoRegistro = new Guid("e0000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Lida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Ocupacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Ocupacoes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Estudante",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Empregado(a)",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Autônomo(a)",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Empresário(a)",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 5L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Aposentado(a)",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = 6L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Desempregado(a)",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = 7L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Outro",
                            VersaoRegistro = new Guid("10000001-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Oportunidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InstituicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("Vagas")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Oportunidades");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoriaId = 3L,
                            Cidade = "Santos",
                            DataFim = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Acao voltada ao fortalecimento do protagonismo da pessoa com deficiencia.",
                            Estado = "SP",
                            Excluido = false,
                            InstituicaoId = 1L,
                            Objetivo = "Promover protagonismo, autonomia e participacao social da pessoa com deficiencia.",
                            Status = 3,
                            Tipo = 0,
                            Titulo = "Programa de Protagonismo da Pessoa com Deficiencia",
                            Vagas = 20,
                            VersaoRegistro = new Guid("00000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            CategoriaId = 2L,
                            Cidade = "Santos",
                            DataFim = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Encontro de acolhimento, escuta e orientacao para maes atipicas e familiares.",
                            Estado = "SP",
                            Excluido = false,
                            InstituicaoId = 1L,
                            Objetivo = "Acolher maes atipicas, fortalecer vinculos e orientar sobre cuidado, direitos e rede de apoio.",
                            Status = 3,
                            Tipo = 1,
                            Titulo = "Encontro de Acolhimento para Maes Atipicas",
                            Vagas = 15,
                            VersaoRegistro = new Guid("00000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            CategoriaId = 3L,
                            Cidade = "Santos",
                            DataFim = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Projeto para estimular autonomia, autoestima, convivencia comunitaria e participacao ativa.",
                            Estado = "SP",
                            Excluido = false,
                            InstituicaoId = 1L,
                            Objetivo = "Incentivar independencia, confianca e inclusao social da pessoa com deficiencia.",
                            Status = 1,
                            Tipo = 2,
                            Titulo = "Projeto Autonomia e Vida Independente",
                            Vagas = 30,
                            VersaoRegistro = new Guid("00000001-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.PalavraBloqueada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Palavra")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Palavra")
                        .IsUnique();

                    b.ToTable("PalavrasBloqueadas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Palavra = "ofensa",
                            VersaoRegistro = new Guid("c0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Palavra = "xingamento",
                            VersaoRegistro = new Guid("c0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Palavra = "discriminacao",
                            VersaoRegistro = new Guid("c0000001-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anonimizado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Anonimizado = false,
                            Ativo = true,
                            Cidade = "Santos",
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@ivg.local",
                            Estado = "SP",
                            Excluido = false,
                            Nome = "Superadmin IVG",
                            Senha = "$2a$11$q1XSDJeu4Dies.apWitrWeqMJz//7NT6dytA.1.BuuftTXiUgc.36",
                            Tipo = 0,
                            VersaoRegistro = new Guid("d0000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Anonimizado = false,
                            Ativo = true,
                            Cidade = "Santos",
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ivg.local",
                            Estado = "SP",
                            Excluido = false,
                            Nome = "Admin Instituto Vitor Gabriel",
                            Senha = "$2a$11$q1XSDJeu4Dies.apWitrWeqMJz//7NT6dytA.1.BuuftTXiUgc.36",
                            Tipo = 2,
                            VersaoRegistro = new Guid("d0000001-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            Anonimizado = false,
                            Ativo = true,
                            Cidade = "Santos",
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "voluntario@ivg.local",
                            Estado = "SP",
                            Excluido = false,
                            Nome = "Voluntario IVG",
                            Senha = "$2a$11$q1XSDJeu4Dies.apWitrWeqMJz//7NT6dytA.1.BuuftTXiUgc.36",
                            Tipo = 3,
                            VersaoRegistro = new Guid("d0000001-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Voluntario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disponibilidade")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Etnia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Habilidades")
                        .HasColumnType("TEXT");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Voluntarios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataInsercao = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataNascimento = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Disponibilidade = "Eventos e encontros",
                            Excluido = false,
                            Genero = "nao informado",
                            Habilidades = "Acolhimento, apoio operacional, cuidado de criancas",
                            UsuarioId = 3L,
                            VersaoRegistro = new Guid("f0000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.VoluntarioFormacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnoConclusao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersaoRegistro")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("VoluntarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("VoluntarioFormacoes");
                });

            modelBuilder.Entity("CategoriaVoluntario", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("AreasAfinidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoluntaMais.Api.Models.Voluntario", null)
                        .WithMany()
                        .HasForeignKey("VoluntariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Feedback", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Inscricao", "Inscricao")
                        .WithMany("Feedbacks")
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscricao");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Inscricao", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Oportunidade", "Oportunidade")
                        .WithMany("Inscricoes")
                        .HasForeignKey("OportunidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoluntaMais.Api.Models.Voluntario", "Voluntario")
                        .WithMany("Inscricoes")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidade");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Instituicao", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Usuario", "Usuario")
                        .WithOne("Instituicao")
                        .HasForeignKey("VoluntaMais.Api.Models.Instituicao", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Notificacao", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Oportunidade", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Categoria", "Categoria")
                        .WithMany("Oportunidades")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("VoluntaMais.Api.Models.Instituicao", "Instituicao")
                        .WithMany("Oportunidades")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Voluntario", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Usuario", "Usuario")
                        .WithOne("Voluntario")
                        .HasForeignKey("VoluntaMais.Api.Models.Voluntario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.VoluntarioFormacao", b =>
                {
                    b.HasOne("VoluntaMais.Api.Models.Voluntario", "Voluntario")
                        .WithMany("Formacoes")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Categoria", b =>
                {
                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Inscricao", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Instituicao", b =>
                {
                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Oportunidade", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Usuario", b =>
                {
                    b.Navigation("Instituicao");

                    b.Navigation("Notificacoes");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("VoluntaMais.Api.Models.Voluntario", b =>
                {
                    b.Navigation("Formacoes");

                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
